//
// Created by Semyon Tikhonenko on 9/9/23.
//

#ifndef ORENDAFORMULA_ORENDAMEASUREMENT_H
#define ORENDAFORMULA_ORENDAMEASUREMENT_H

enum OrendaMeasurement {
    ORENDA_USA, ORENDA_METRIC
};

#endif //ORENDAFORMULA_ORENDAMEASUREMENT_H
